In [827]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [828]:
#Definir función sigmoide
def sigmoid(x):
 return 1/ (1+np.exp(-x))

#Definir la derivada de la función sigmoide
def sigmoidPrime(x):
    return np.exp(-x)/((1+np.exp(-x))**2)

In [829]:

def forward_propagation(X):
    
    # Definir los pesos y los sesgos para la capa de entrada a la capa oculta
    #np.random.seed(10)
    #WhX = np.random.rand(3,4)
    
    np.random.seed(20)
    b1 = np.random.rand(1,4)

    # Calcular la suma ponderada en la capa oculta
    z1 = np.dot(X,WhX) + b1

    # Aplicar la función de activación a la capa oculta
    a1 = sigmoid(z1)

    # Definir los pesos y sesgos para la capa oculta a la capa de salida
    #np.random.seed(30)
    #WhY = np.random.rand(4,1)
    np.random.seed(40)
    b2 = np.random.rand(1)

    # Calcular la suma ponderada en la capa de salida
    z2 = np.dot(a1,WhY) + b2

    # Aplicar la función de activación a la capa de salida
    y_hat = sigmoid(z2)

    return y_hat



In [830]:
#Definir la back propagation.
def backword_prop(y,y_hat, z1, a1, z2,alpha):
    global WhX, WhY
    
    # Calcular la derivada de la función de pérdida con respecto a la salida de la capa de salida
    delta2 = np.multiply(-(y - y_hat), sigmoidPrime(z2))
    
    # Calcular el gradiente con respecto a los pesos y sesgos de la capa de salida
    dJ_dWhY = np.dot(a1.T, delta2)
    
    # Calcular la retropropagación del error a la capa oculta
    delta1 = np.dot(delta2, WhY.T) * sigmoidPrime(z1)
    
    # Calcular el gradiente con respecto a los pesos y sesgos de la capa oculta
    dJ_dWhX = np.dot(X.T, delta1)
    
    # Actualizar los pesos de la capa oculta y de la capa de salida utilizando el descenso de gradiente
    WhX = WhX - alpha * dJ_dWhX
    WhY = WhY - alpha * dJ_dWhY
    
    return WhX, WhY

In [837]:
y=1
alpha = .015

np.random.seed(10)
WhX = np.random.rand(3,4)
np.random.seed(52)
WhY = np.random.rand(4,1)

X = np.array([[.01, .03, .05]])
y_hat = forward_propagation(X)
print('Pesos WhX 1:\n', WhX)
print('Pesos WhY 1:\n', WhY)
print('y estimada 1: ', y_hat)
WhX,WhY = backword_prop(y,y_hat, z1, a1, z2,alpha)

Pesos WhX 1:
 [[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]]
Pesos WhY 1:
 [[0.82311034]
 [0.02611798]
 [0.21077064]
 [0.61842177]]
y estimada 1:  [[0.82516326]]


In [838]:
X = np.array([[.02, .04, .06]])
y_hat = forward_propagation(X)
print('Pesos WhX 2:\n',WhX)
print('Pesos WhY 2:\n', WhY)
print('y estimada 2: ',y_hat)
WhX,WhY = backword_prop(y,y_hat, z1, a1, z2,alpha)

Pesos WhX 2:
 [[0.7713214  0.02075198 0.63364838 0.74880421]
 [0.4985093  0.22479673 0.19806329 0.76053168]
 [0.16911464 0.08833995 0.68536053 0.95339496]]
Pesos WhY 2:
 [[0.82352289]
 [0.02651058]
 [0.21122349]
 [0.61889475]]
y estimada 2:  [[0.82626947]]


In [839]:
X = np.array([[.05, .07, .09]])
y_hat =forward_propagation(X)
print('Pesos WhX 3:\n',WhX)
print('Pesos WhY 3:\n', WhY)
print('y estimada 3: ',y_hat)
WhX,WhY = backword_prop(y,y_hat, z1, a1, z2,alpha)

Pesos WhX 3:
 [[0.77132292 0.02075203 0.63364866 0.74880485]
 [0.49851232 0.22479683 0.19806385 0.76053297]
 [0.16911918 0.08834011 0.68536137 0.95339689]]
Pesos WhY 3:
 [[0.82393284]
 [0.0269007 ]
 [0.21167347]
 [0.61936474]]
y estimada 3:  [[0.82917259]]


In [841]:
X = np.array([[.05, .07, .09]])
y_hat = forward_propagation(X)
print('Pesos WhX 4:\n',WhX)
print('Pesos WhY 4:\n', WhY)
print('y estimada 4: ',y_hat)

Pesos WhX 4:
 [[0.77132664 0.02075217 0.63364935 0.74880643]
 [0.49851753 0.22479702 0.19806483 0.76053518]
 [0.16912588 0.08834035 0.68536262 0.95339974]]
Pesos WhY 4:
 [[0.82433593]
 [0.0272843 ]
 [0.21211593]
 [0.61982688]]
y estimada 4:  [[0.82934285]]
