# Propagacion hacia adelante

In [41]:
import pandas as pd
import numpy as np
import math

### Se define una red neuronal con las siguientes caracteristicas
1. Una capa de entrada con dos inputs, x1 y x2.
2. Una capa oculta con 4 neuronas h1, h2, h3 y h4.
3. Una capa de salida con 1 neurona o1

In [42]:
inputs = []


In [43]:
# Inicializar los pesos de las 4 neuronas en la capa oculta
Wxh = np.array([[.2, .65, .45, .12],
                [.8, .35, .55, .15]])
print(Wxh)

[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


In [44]:
# Inicializar los pesos de la neurona enla capa de salida
Why = np.array([[.2], [.35], [.45], [.52]])
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


In [45]:
# Inicializar los sesgos en la capa oculta
bh = np.array([[.2], [.15], [.45], [.23]])
print(bh)

[[0.2 ]
 [0.15]
 [0.45]
 [0.23]]


In [46]:
by = .5

In [47]:
# Definir la funcion Sigmoide
def sigmoide(x):
    return 1 / (1 + np.exp(-x))

In [48]:
def forward_prop(x):
    z1 = np.dot(x,Wxh) + bh # Capa oculta
    a1 = sigmoide(z1) # Capa oculta

    z2 = np.dot(a1,Why) + by # Capa de salida
    y_estimado = sigmoide(z2)

    return y_estimado

In [49]:
x = np.array([1.75, 70])
y = forward_prop(x)
y

array([[0.88288003],
       [0.88287998],
       [0.88288024],
       [0.88288006]])